### ISSUE TITLE
more general functions to build plan segments

### ISSUE THREAD

**Issue by diazrenata** [weecology/MATSS-LDATS#14]
I've been making new functions to add steps to the pipeline that depend on targets from the previous step. (TS_on_LDA runs on the outputs from LDA_set, etc). There might be a way to make these more general?

**Comment by ha0ye** [comment]
Agreed. I think there can probably be a general function that produces a plan that applies all the steps of the LDATS analysis to the datasets.

**Comment by diazrenata** [comment]
I think this function now exists (`build_ldats_plans`) with options. :tada:
